<?php

/* @var Magento\Catalog\Block\Category\View $block */

use Magento\Catalog\Helper\Output;

?>
<?php if ($_bottomDescription = $block->getCurrentCategory()->getData('bottom_description')): ?>
    <div class="category-bottom-description">
        <?= /* @escapeNotVerified */ $this->helper(Output::class)->categoryAttribute($block->getCurrentCategory(), $_bottomDescription, 'bottom_description') ?>
    </div>
<?php endif; ?>
